name: Push to other

on:
  push:
    branches: "*"
    ranches-ignore: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TERM: xterm-256color
        run: make build
